### ISSUE TITLE
Would love to have available a PL/SQL script in order to build up the Oracle database structure

### ISSUE THREAD

**Issue by enriqueortegagarcia** [salahatwa/Hospital-Management-System#2]
Would love to have available a PL/SQL script in order to build up the Oracle database structure
of the system. Also some kind of help with PORTS-Conectivity to Oracle_11g from the website.
("port 8080 already in use..." Is the port Oracle_1512 the defective port used by the program?,...). I have compiled, solved +700 errors on my EclipseJEE IDE, setup the Tomcat v8.5.32 server, the website arises on localhost:8080,...but unable to enter usernames, patients, passwords, doctors,...logically as the Oracle environment has no structure, tables,usernames...build up. 
Perhaps am I asking too much from your kindness !!!???. Please answer.

Enrique Ortega Garcia.
eortega7@gmail.com

**Comment by salahatwa** [comment]
database script uploaded .
